// Danh sách quận/huyện tiêu biểu theo tỉnh/thành — chỉ dùng để sinh tên cộng đồng VIP (client-side).
export const VN_DISTRICTS: Record<string, string[]> = {
  "An Giang": ["Long Xuyên", "Châu Đốc", "Tân Châu", "Chợ Mới", "Tri Tôn", "Thoại Sơn"],
  "Bà Rịa - Vũng Tàu": ["Vũng Tàu", "Bà Rịa", "Phú Mỹ", "Long Điền", "Đất Đỏ", "Xuyên Mộc"],
  "Bạc Liêu": ["Bạc Liêu", "Giá Rai", "Hòa Bình", "Vĩnh Lợi", "Đông Hải", "Phước Long"],
  "Bắc Giang": ["Bắc Giang", "Việt Yên", "Hiệp Hòa", "Lạng Giang", "Tân Yên", "Yên Dũng"],
  "Bắc Kạn": ["Bắc Kạn", "Chợ Mới", "Ba Bể", "Na Rì", "Ngân Sơn", "Bạch Thông"],
  "Bắc Ninh": ["Bắc Ninh", "Từ Sơn", "Yên Phong", "Quế Võ", "Tiên Du", "Thuận Thành"],
  "Bến Tre": ["Bến Tre", "Châu Thành", "Mỏ Cày Nam", "Giồng Trôm", "Ba Tri", "Bình Đại"],
  "Bình Dương": ["Thủ Dầu Một", "Dĩ An", "Thuận An", "Tân Uyên", "Bến Cát", "Bàu Bàng", "Phú Giáo"],
  "Bình Định": ["Quy Nhơn", "An Nhơn", "Hoài Nhơn", "Tuy Phước", "Phù Cát", "Tây Sơn"],
  "Bình Phước": ["Đồng Xoài", "Bình Long", "Phước Long", "Chơn Thành", "Lộc Ninh", "Bù Đăng"],
  "Bình Thuận": ["Phan Thiết", "La Gi", "Hàm Thuận Bắc", "Hàm Thuận Nam", "Tuy Phong", "Đức Linh"],
  "Cà Mau": ["Cà Mau", "Năm Căn", "Đầm Dơi", "Cái Nước", "Trần Văn Thời", "U Minh"],
  "Cao Bằng": ["Cao Bằng", "Trùng Khánh", "Hà Quảng", "Bảo Lạc", "Quảng Hòa", "Nguyên Bình"],
  "Cần Thơ": ["Ninh Kiều", "Bình Thủy", "Cái Răng", "Ô Môn", "Thốt Nốt", "Phong Điền"],
  "Đà Nẵng": ["Hải Châu", "Thanh Khê", "Sơn Trà", "Ngũ Hành Sơn", "Liên Chiểu", "Cẩm Lệ"],
  "Đắk Lắk": ["Buôn Ma Thuột", "Buôn Hồ", "Ea Kar", "Krông Pắc", "Cư M'gar", "Ea H'leo"],
  "Đắk Nông": ["Gia Nghĩa", "Đắk Mil", "Đắk R'lấp", "Cư Jút", "Krông Nô", "Đắk Song"],
  "Điện Biên": ["Điện Biên Phủ", "Mường Lay", "Tuần Giáo", "Mường Ảng", "Tủa Chùa", "Mường Chà"],
  "Đồng Nai": ["Biên Hòa", "Long Khánh", "Trảng Bom", "Long Thành", "Nhơn Trạch", "Vĩnh Cửu"],
  "Đồng Tháp": ["Cao Lãnh", "Sa Đéc", "Hồng Ngự", "Tháp Mười", "Lấp Vò", "Châu Thành"],
  "Gia Lai": ["Pleiku", "An Khê", "Ayun Pa", "Chư Sê", "Chư Prông", "Đắk Đoa"],
  "Hà Giang": ["Hà Giang", "Đồng Văn", "Mèo Vạc", "Bắc Quang", "Vị Xuyên", "Quản Bạ"],
  "Hà Nam": ["Phủ Lý", "Duy Tiên", "Kim Bảng", "Lý Nhân", "Thanh Liêm", "Bình Lục"],
  "Hà Nội": ["Hoàn Kiếm", "Cầu Giấy", "Đống Đa", "Hà Đông", "Long Biên", "Thanh Xuân", "Nam Từ Liêm"],
  "Hà Tĩnh": ["Hà Tĩnh", "Hồng Lĩnh", "Kỳ Anh", "Thạch Hà", "Can Lộc", "Nghi Xuân"],
  "Hải Dương": ["Hải Dương", "Chí Linh", "Kinh Môn", "Cẩm Giàng", "Bình Giang", "Gia Lộc"],
  "Hải Phòng": ["Hồng Bàng", "Lê Chân", "Ngô Quyền", "Hải An", "Kiến An", "Đồ Sơn", "Thủy Nguyên"],
  "Hậu Giang": ["Vị Thanh", "Ngã Bảy", "Long Mỹ", "Châu Thành", "Phụng Hiệp", "Vị Thủy"],
  "Hòa Bình": ["Hòa Bình", "Lương Sơn", "Mai Châu", "Tân Lạc", "Kim Bôi", "Lạc Thủy"],
  "Hưng Yên": ["Hưng Yên", "Mỹ Hào", "Văn Lâm", "Yên Mỹ", "Khoái Châu", "Văn Giang"],
  "Khánh Hòa": ["Nha Trang", "Cam Ranh", "Ninh Hòa", "Vạn Ninh", "Diên Khánh", "Cam Lâm"],
  "Kiên Giang": ["Rạch Giá", "Hà Tiên", "Phú Quốc", "Kiên Lương", "Gò Quao", "An Biên"],
  "Kon Tum": ["Kon Tum", "Ngọc Hồi", "Đắk Hà", "Sa Thầy", "Đắk Tô", "Kon Plông"],
  "Lai Châu": ["Lai Châu", "Tam Đường", "Than Uyên", "Phong Thổ", "Sìn Hồ", "Mường Tè"],
  "Lạng Sơn": ["Lạng Sơn", "Hữu Lũng", "Chi Lăng", "Cao Lộc", "Lộc Bình", "Bắc Sơn"],
  "Lào Cai": ["Lào Cai", "Sa Pa", "Bảo Thắng", "Bát Xát", "Bảo Yên", "Văn Bàn"],
  "Lâm Đồng": ["Đà Lạt", "Bảo Lộc", "Đức Trọng", "Di Linh", "Lâm Hà", "Đơn Dương"],
  "Long An": ["Tân An", "Bến Lức", "Đức Hòa", "Cần Giuộc", "Cần Đước", "Thủ Thừa"],
  "Nam Định": ["Nam Định", "Giao Thủy", "Hải Hậu", "Xuân Trường", "Ý Yên", "Nghĩa Hưng"],
  "Nghệ An": ["Vinh", "Cửa Lò", "Thái Hòa", "Diễn Châu", "Quỳnh Lưu", "Đô Lương"],
  "Ninh Bình": ["Ninh Bình", "Tam Điệp", "Hoa Lư", "Nho Quan", "Kim Sơn", "Yên Khánh"],
  "Ninh Thuận": ["Phan Rang - Tháp Chàm", "Ninh Hải", "Ninh Phước", "Ninh Sơn", "Thuận Bắc", "Thuận Nam"],
  "Phú Thọ": ["Việt Trì", "Phú Thọ", "Lâm Thao", "Thanh Ba", "Cẩm Khê", "Đoan Hùng"],
  "Phú Yên": ["Tuy Hòa", "Sông Cầu", "Đông Hòa", "Tuy An", "Phú Hòa", "Sơn Hòa"],
  "Quảng Bình": ["Đồng Hới", "Ba Đồn", "Bố Trạch", "Lệ Thủy", "Quảng Trạch", "Tuyên Hóa"],
  "Quảng Nam": ["Tam Kỳ", "Hội An", "Điện Bàn", "Duy Xuyên", "Thăng Bình", "Núi Thành"],
  "Quảng Ngãi": ["Quảng Ngãi", "Đức Phổ", "Bình Sơn", "Sơn Tịnh", "Mộ Đức", "Tư Nghĩa"],
  "Quảng Ninh": ["Hạ Long", "Cẩm Phả", "Uông Bí", "Móng Cái", "Đông Triều", "Quảng Yên", "Vân Đồn"],
  "Quảng Trị": ["Đông Hà", "Quảng Trị", "Vĩnh Linh", "Gio Linh", "Triệu Phong", "Hải Lăng"],
  "Sóc Trăng": ["Sóc Trăng", "Vĩnh Châu", "Ngã Năm", "Mỹ Xuyên", "Kế Sách", "Long Phú"],
  "Sơn La": ["Sơn La", "Mộc Châu", "Mai Sơn", "Thuận Châu", "Phù Yên", "Sông Mã"],
  "Tây Ninh": ["Tây Ninh", "Trảng Bàng", "Hòa Thành", "Gò Dầu", "Dương Minh Châu", "Châu Thành"],
  "Thái Bình": ["Thái Bình", "Tiền Hải", "Kiến Xương", "Đông Hưng", "Quỳnh Phụ", "Vũ Thư"],
  "Thái Nguyên": ["Thái Nguyên", "Sông Công", "Phổ Yên", "Đại Từ", "Phú Bình", "Đồng Hỷ"],
  "Thanh Hóa": ["Thanh Hóa", "Sầm Sơn", "Bỉm Sơn", "Nghi Sơn", "Hoằng Hóa", "Quảng Xương"],
  "Thừa Thiên Huế": ["Huế", "Hương Thủy", "Hương Trà", "Phú Vang", "Phong Điền", "Quảng Điền"],
  "Tiền Giang": ["Mỹ Tho", "Gò Công", "Cai Lậy", "Châu Thành", "Chợ Gạo", "Cái Bè"],
  "TP. Hồ Chí Minh": ["Quận 1", "Quận 3", "Quận 7", "Bình Thạnh", "Gò Vấp", "Tân Bình", "Thủ Đức"],
  "Trà Vinh": ["Trà Vinh", "Duyên Hải", "Càng Long", "Cầu Kè", "Tiểu Cần", "Trà Cú"],
  "Tuyên Quang": ["Tuyên Quang", "Sơn Dương", "Yên Sơn", "Hàm Yên", "Chiêm Hóa", "Na Hang"],
  "Vĩnh Long": ["Vĩnh Long", "Bình Minh", "Long Hồ", "Tam Bình", "Trà Ôn", "Mang Thít"],
  "Vĩnh Phúc": ["Vĩnh Yên", "Phúc Yên", "Bình Xuyên", "Yên Lạc", "Vĩnh Tường", "Tam Dương"],
  "Yên Bái": ["Yên Bái", "Nghĩa Lộ", "Văn Chấn", "Lục Yên", "Trấn Yên", "Mù Cang Chải"],
};

export function districtsOf(province: string): string[] {
  return VN_DISTRICTS[province] ?? [province];
}
