export const LANGUAGES = [
  { code: "vi", flag: "🇻🇳", name: "Tiếng Việt", htmlLang: "vi" },
  { code: "zh-TW", flag: "🇹🇼", name: "繁體中文", htmlLang: "zh-Hant" },
  { code: "zh-CN", flag: "🇨🇳", name: "简体中文", htmlLang: "zh-Hans" },
  { code: "en", flag: "🇺🇸", name: "English", htmlLang: "en" },
  { code: "ja", flag: "🇯🇵", name: "日本語", htmlLang: "ja" },
] as const;
export type AppLanguage = (typeof LANGUAGES)[number]["code"];
export const DEFAULT_LANGUAGE: AppLanguage = "vi";
export const messages = {
 vi:{language:"Ngôn ngữ",chooseLanguage:"Chọn ngôn ngữ",closeLanguage:"Đóng menu ngôn ngữ",close:"Đóng",back:"Quay lại",home:"Trang chủ",messages:"Tin nhắn",profile:"Hồ sơ",feedback:"Feedback",notifications:"Thông báo",search:"Tìm kiếm",save:"Lưu",cancel:"Hủy",delete:"Xóa",edit:"Sửa",add:"Thêm",confirm:"Xác nhận",continue:"Tiếp tục",login:"Đăng nhập",logout:"Đăng xuất",register:"Đăng ký",loading:"Đang tải…",error:"Đã xảy ra lỗi",retry:"Thử lại",empty:"Không có dữ liệu",settings:"Cài đặt",status:"Trạng thái",manage:"Quản lý",customer:"Khách hàng",password:"Mật khẩu",phone:"Số Zalo",submit:"Gửi",done:"Đã hiểu",website:"Về Website",mainNav:"Điều hướng chính",live:"Live Mốc",goHome:"Về trang chủ",wallet:"Số dư ví",hideBalance:"Ẩn số dư",showBalance:"Hiện số dư",openMenu:"Mở menu",adminPanel:"Admin Panel",healthy:"Hệ thống hoạt động ổn định",quickSearch:"Tìm nhanh…"},
 "zh-TW":{language:"語言",chooseLanguage:"選擇語言",closeLanguage:"關閉語言選單",close:"關閉",back:"返回",home:"首頁",messages:"訊息",profile:"個人檔案",feedback:"意見回饋",notifications:"通知",search:"搜尋",save:"儲存",cancel:"取消",delete:"刪除",edit:"編輯",add:"新增",confirm:"確認",continue:"繼續",login:"登入",logout:"登出",register:"註冊",loading:"載入中…",error:"發生錯誤",retry:"重試",empty:"沒有資料",settings:"設定",status:"狀態",manage:"管理",customer:"客戶",password:"密碼",phone:"Zalo 號碼",submit:"送出",done:"知道了",website:"返回網站",mainNav:"主選單",live:"直播",goHome:"返回首頁",wallet:"錢包餘額",hideBalance:"隱藏餘額",showBalance:"顯示餘額",openMenu:"開啟選單",adminPanel:"管理後台",healthy:"系統運作正常",quickSearch:"快速搜尋…"},
 "zh-CN":{language:"语言",chooseLanguage:"选择语言",closeLanguage:"关闭语言菜单",close:"关闭",back:"返回",home:"首页",messages:"消息",profile:"个人资料",feedback:"反馈",notifications:"通知",search:"搜索",save:"保存",cancel:"取消",delete:"删除",edit:"编辑",add:"添加",confirm:"确认",continue:"继续",login:"登录",logout:"退出登录",register:"注册",loading:"加载中…",error:"发生错误",retry:"重试",empty:"暂无数据",settings:"设置",status:"状态",manage:"管理",customer:"客户",password:"密码",phone:"Zalo 号码",submit:"提交",done:"知道了",website:"返回网站",mainNav:"主导航",live:"直播",goHome:"返回首页",wallet:"钱包余额",hideBalance:"隐藏余额",showBalance:"显示余额",openMenu:"打开菜单",adminPanel:"管理后台",healthy:"系统运行正常",quickSearch:"快速搜索…"},
 en:{language:"Language",chooseLanguage:"Choose language",closeLanguage:"Close language menu",close:"Close",back:"Back",home:"Home",messages:"Messages",profile:"Profile",feedback:"Feedback",notifications:"Notifications",search:"Search",save:"Save",cancel:"Cancel",delete:"Delete",edit:"Edit",add:"Add",confirm:"Confirm",continue:"Continue",login:"Login",logout:"Log out",register:"Register",loading:"Loading…",error:"An error occurred",retry:"Try again",empty:"No data",settings:"Settings",status:"Status",manage:"Manage",customer:"Customer",password:"Password",phone:"Zalo number",submit:"Submit",done:"Got it",website:"Back to website",mainNav:"Main navigation",live:"Live",goHome:"Go to home",wallet:"Wallet balance",hideBalance:"Hide balance",showBalance:"Show balance",openMenu:"Open menu",adminPanel:"Admin Panel",healthy:"System operating normally",quickSearch:"Quick search…"},
 ja:{language:"言語",chooseLanguage:"言語を選択",closeLanguage:"言語メニューを閉じる",close:"閉じる",back:"戻る",home:"ホーム",messages:"メッセージ",profile:"プロフィール",feedback:"フィードバック",notifications:"通知",search:"検索",save:"保存",cancel:"キャンセル",delete:"削除",edit:"編集",add:"追加",confirm:"確認",continue:"続ける",login:"ログイン",logout:"ログアウト",register:"登録",loading:"読み込み中…",error:"エラーが発生しました",retry:"再試行",empty:"データがありません",settings:"設定",status:"ステータス",manage:"管理",customer:"顧客",password:"パスワード",phone:"Zalo番号",submit:"送信",done:"了解",website:"サイトに戻る",mainNav:"メインナビゲーション",live:"ライブ",goHome:"ホームへ",wallet:"ウォレット残高",hideBalance:"残高を隠す",showBalance:"残高を表示",openMenu:"メニューを開く",adminPanel:"管理パネル",healthy:"システムは正常です",quickSearch:"クイック検索…"}
} as const;
export type TranslationKey = keyof typeof messages.vi;
