-- =====================================================================
-- ✊ ✋ ✌ KÉO • BÚA • BAO (PvP Realtime) — chạy trên DB CŨ qua Supabase SQL Editor
-- Idempotent. Toàn bộ logic tiền + kết quả do SERVER quyết định.
-- File này cũng XÓA HOÀN TOÀN mini game Bao Lì Xì / số ngẫu nhiên cũ.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0) XOÁ mini game cũ (Bao Lì Xì + số ngẫu nhiên)
-- ---------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.lucky_game_state() CASCADE;
DROP FUNCTION IF EXISTS public.lucky_game_place_bet(bigint, int, bigint) CASCADE;
DROP FUNCTION IF EXISTS public.lucky_game_place_bet(bigint, integer, bigint) CASCADE;
DROP FUNCTION IF EXISTS public.lucky_game_admin_update(jsonb) CASCADE;
DROP FUNCTION IF EXISTS public.lucky_game_admin_force_end() CASCADE;
DROP FUNCTION IF EXISTS public.lucky_game_settle(bigint) CASCADE;
DROP TABLE IF EXISTS public.lucky_game_bets CASCADE;
DROP TABLE IF EXISTS public.lucky_game_sessions CASCADE;
DROP TABLE IF EXISTS public.lucky_game_config CASCADE;

-- ---------------------------------------------------------------------
-- 1) Bảng phòng
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.rps_rooms (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            text   NOT NULL UNIQUE,
  stake           bigint NOT NULL CHECK (stake > 0),
  creator_id      uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  opponent_id     uuid            REFERENCES auth.users(id) ON DELETE SET NULL,
  status          text   NOT NULL DEFAULT 'waiting'
                  CHECK (status IN ('waiting','playing','done','cancelled')),
  creator_choice  text CHECK (creator_choice IN ('rock','paper','scissors')),
  opponent_choice text CHECK (opponent_choice IN ('rock','paper','scissors')),
  winner_id       uuid,
  is_draw         boolean NOT NULL DEFAULT false,
  prepare_ends_at timestamptz,   -- hết 10s "Chuẩn bị..."
  choose_ends_at  timestamptz,   -- hết 5s chọn tay
  created_at      timestamptz NOT NULL DEFAULT now(),
  finished_at     timestamptz
);
CREATE INDEX IF NOT EXISTS rps_rooms_status_idx  ON public.rps_rooms (status, id DESC);
CREATE INDEX IF NOT EXISTS rps_rooms_creator_idx ON public.rps_rooms (creator_id);

-- 2) Chat trong phòng
CREATE TABLE IF NOT EXISTS public.rps_messages (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id    bigint NOT NULL REFERENCES public.rps_rooms(id) ON DELETE CASCADE,
  user_id    uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  body       text   NOT NULL CHECK (char_length(body) BETWEEN 1 AND 200),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS rps_messages_room_idx ON public.rps_messages (room_id, id DESC);

-- 3) Khán giả (heartbeat)
CREATE TABLE IF NOT EXISTS public.rps_viewers (
  room_id   bigint NOT NULL REFERENCES public.rps_rooms(id) ON DELETE CASCADE,
  user_id   uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  last_seen timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (room_id, user_id)
);

GRANT SELECT ON public.rps_rooms    TO authenticated, anon;
GRANT SELECT ON public.rps_messages TO authenticated;
GRANT SELECT ON public.rps_viewers  TO authenticated;
GRANT ALL    ON public.rps_rooms    TO service_role;
GRANT ALL    ON public.rps_messages TO service_role;
GRANT ALL    ON public.rps_viewers  TO service_role;

ALTER TABLE public.rps_rooms    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rps_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rps_viewers  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "rps rooms read" ON public.rps_rooms;
CREATE POLICY "rps rooms read" ON public.rps_rooms
  FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS "rps messages read" ON public.rps_messages;
CREATE POLICY "rps messages read" ON public.rps_messages
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "rps viewers read" ON public.rps_viewers;
CREATE POLICY "rps viewers read" ON public.rps_viewers
  FOR SELECT TO authenticated USING (true);
-- Mọi ghi chỉ qua RPC SECURITY DEFINER.

-- 4) Realtime
DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.rps_rooms;
  EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.rps_messages;
  EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_object THEN NULL; END;
END $$;
ALTER TABLE public.rps_rooms    REPLICA IDENTITY FULL;
ALTER TABLE public.rps_messages REPLICA IDENTITY FULL;

-- ---------------------------------------------------------------------
-- 5) Helper: cộng/trừ Coin (tôn trọng guard app.allow_gem_change nếu có)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_add_coin(p_user uuid, p_delta bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM set_config('app.allow_gem_change',  '1', true);
  PERFORM set_config('app.allow_candy_change','1', true);
  UPDATE public.profiles
     SET gem_balance = GREATEST(0, COALESCE(gem_balance,0) + p_delta)
   WHERE id = p_user;
END $$;

-- ---------------------------------------------------------------------
-- 6) Settle một phòng (gọi khi hết giờ chọn hoặc đủ 2 lựa chọn)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_settle(p_room_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r        public.rps_rooms%rowtype;
  v_winner uuid;
  v_draw   boolean := false;
BEGIN
  SELECT * INTO r FROM public.rps_rooms WHERE id = p_room_id FOR UPDATE;
  IF r.id IS NULL OR r.status <> 'playing' THEN RETURN; END IF;

  IF r.creator_choice IS NULL AND r.opponent_choice IS NULL THEN
    v_draw := true;                                   -- cả hai treo → hòa, hoàn tiền
  ELSIF r.creator_choice IS NULL THEN
    v_winner := r.opponent_id;                        -- không chọn → thua
  ELSIF r.opponent_choice IS NULL THEN
    v_winner := r.creator_id;
  ELSIF r.creator_choice = r.opponent_choice THEN
    v_draw := true;
  ELSIF (r.creator_choice, r.opponent_choice) IN
        (('rock','scissors'), ('paper','rock'), ('scissors','paper')) THEN
    v_winner := r.creator_id;
  ELSE
    v_winner := r.opponent_id;
  END IF;

  IF v_draw THEN
    PERFORM public.rps_add_coin(r.creator_id, r.stake);
    IF r.opponent_id IS NOT NULL THEN
      PERFORM public.rps_add_coin(r.opponent_id, r.stake);
    END IF;
  ELSE
    PERFORM public.rps_add_coin(v_winner, r.stake * 2);
  END IF;

  UPDATE public.rps_rooms
     SET status = 'done', winner_id = v_winner, is_draw = v_draw, finished_at = now()
   WHERE id = p_room_id;
END $$;

-- ---------------------------------------------------------------------
-- 7) Tick: đẩy trạng thái theo thời gian server + dọn phòng cũ
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_tick()
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE r record;
BEGIN
  -- Hết giờ chọn → settle
  FOR r IN SELECT id FROM public.rps_rooms
            WHERE status = 'playing' AND choose_ends_at IS NOT NULL AND now() > choose_ends_at
  LOOP
    PERFORM public.rps_settle(r.id);
  END LOOP;

  -- Phòng chờ quá 10 phút không ai vào → hủy, hoàn tiền người tạo
  FOR r IN SELECT id, creator_id, stake FROM public.rps_rooms
            WHERE status = 'waiting' AND created_at < now() - interval '10 minutes'
  LOOP
    PERFORM public.rps_add_coin(r.creator_id, r.stake);
    UPDATE public.rps_rooms SET status = 'cancelled', finished_at = now() WHERE id = r.id;
  END LOOP;

  -- Dọn phòng đã kết thúc > 1 giờ
  DELETE FROM public.rps_rooms
   WHERE status IN ('done','cancelled') AND finished_at < now() - interval '1 hour';
END $$;

-- ---------------------------------------------------------------------
-- 8) Danh sách phòng
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_list_rooms()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_me uuid := auth.uid(); v_out jsonb;
BEGIN
  PERFORM public.rps_tick();
  SELECT jsonb_build_object(
    'now', now(),
    'balance', (SELECT COALESCE(gem_balance,0) FROM public.profiles WHERE id = v_me),
    'my_room_id', (SELECT id FROM public.rps_rooms
                    WHERE status IN ('waiting','playing')
                      AND (creator_id = v_me OR opponent_id = v_me)
                    ORDER BY id DESC LIMIT 1),
    'rooms', COALESCE((
      SELECT jsonb_agg(x ORDER BY (x->>'id')::bigint DESC) FROM (
        SELECT jsonb_build_object(
          'id', r.id, 'code', r.code, 'stake', r.stake, 'status', r.status,
          'creator_id', r.creator_id, 'opponent_id', r.opponent_id,
          'creator_name', cp.full_name, 'creator_avatar', cp.avatar,
          'opponent_name', op.full_name, 'opponent_avatar', op.avatar,
          'viewers', (SELECT count(*) FROM public.rps_viewers v
                       WHERE v.room_id = r.id AND v.last_seen > now() - interval '30 seconds')
        ) AS x
        FROM public.rps_rooms r
        LEFT JOIN public.profiles cp ON cp.id = r.creator_id
        LEFT JOIN public.profiles op ON op.id = r.opponent_id
        WHERE r.status IN ('waiting','playing')
        ORDER BY r.id DESC LIMIT 50
      ) s
    ), '[]'::jsonb)
  ) INTO v_out;
  RETURN v_out;
END $$;

-- Đếm nhanh số phòng đang hoạt động (cho badge LIVE ở thanh điều hướng)
CREATE OR REPLACE FUNCTION public.rps_active_count()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT jsonb_build_object(
    'waiting', (SELECT count(*) FROM public.rps_rooms WHERE status = 'waiting'),
    'playing', (SELECT count(*) FROM public.rps_rooms WHERE status = 'playing')
  );
$$;

-- ---------------------------------------------------------------------
-- 9) Tạo phòng (khóa tiền ngay)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_create_room(p_stake bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_me uuid := auth.uid(); v_bal bigint; v_id bigint; v_code text;
BEGIN
  IF v_me IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
  IF p_stake NOT IN (10000,20000,50000,100000,200000,500000,1000000) THEN
    RAISE EXCEPTION 'INVALID_STAKE';
  END IF;
  PERFORM public.rps_tick();

  IF EXISTS (SELECT 1 FROM public.rps_rooms
              WHERE status IN ('waiting','playing')
                AND (creator_id = v_me OR opponent_id = v_me)) THEN
    RAISE EXCEPTION 'ALREADY_IN_ROOM';
  END IF;

  SELECT COALESCE(gem_balance,0) INTO v_bal FROM public.profiles WHERE id = v_me FOR UPDATE;
  IF v_bal IS NULL OR v_bal < p_stake THEN RAISE EXCEPTION 'INSUFFICIENT_BALANCE'; END IF;

  PERFORM public.rps_add_coin(v_me, -p_stake);

  LOOP
    v_code := lpad((floor(random() * 90000) + 10000)::int::text, 5, '0');
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.rps_rooms WHERE code = v_code);
  END LOOP;

  INSERT INTO public.rps_rooms (code, stake, creator_id)
  VALUES (v_code, p_stake, v_me) RETURNING id INTO v_id;

  RETURN jsonb_build_object('ok', true, 'room_id', v_id, 'code', v_code);
END $$;

-- ---------------------------------------------------------------------
-- 10) Vào phòng (khóa tiền, phòng thành FULL và bắt đầu đếm 10s)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_join_room(p_room_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_me uuid := auth.uid(); r public.rps_rooms%rowtype; v_bal bigint;
BEGIN
  IF v_me IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
  PERFORM public.rps_tick();

  SELECT * INTO r FROM public.rps_rooms WHERE id = p_room_id FOR UPDATE;
  IF r.id IS NULL THEN RAISE EXCEPTION 'ROOM_NOT_FOUND'; END IF;
  IF r.status <> 'waiting' OR r.opponent_id IS NOT NULL THEN RAISE EXCEPTION 'ROOM_FULL'; END IF;
  IF r.creator_id = v_me THEN RAISE EXCEPTION 'OWN_ROOM'; END IF;

  IF EXISTS (SELECT 1 FROM public.rps_rooms
              WHERE status IN ('waiting','playing')
                AND (creator_id = v_me OR opponent_id = v_me)) THEN
    RAISE EXCEPTION 'ALREADY_IN_ROOM';
  END IF;

  SELECT COALESCE(gem_balance,0) INTO v_bal FROM public.profiles WHERE id = v_me FOR UPDATE;
  IF v_bal IS NULL OR v_bal < r.stake THEN RAISE EXCEPTION 'INSUFFICIENT_BALANCE'; END IF;

  PERFORM public.rps_add_coin(v_me, -r.stake);

  UPDATE public.rps_rooms
     SET opponent_id = v_me,
         status = 'playing',
         prepare_ends_at = now() + interval '10 seconds',
         choose_ends_at  = now() + interval '18 seconds'   -- 10s chuẩn bị + 3s đếm + 5s chọn
   WHERE id = p_room_id;

  RETURN jsonb_build_object('ok', true, 'room_id', p_room_id);
END $$;

-- ---------------------------------------------------------------------
-- 11) Chọn tay
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_choose(p_room_id bigint, p_choice text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_me uuid := auth.uid(); r public.rps_rooms%rowtype;
BEGIN
  IF v_me IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
  IF p_choice NOT IN ('rock','paper','scissors') THEN RAISE EXCEPTION 'INVALID_CHOICE'; END IF;

  SELECT * INTO r FROM public.rps_rooms WHERE id = p_room_id FOR UPDATE;
  IF r.id IS NULL THEN RAISE EXCEPTION 'ROOM_NOT_FOUND'; END IF;
  IF r.status <> 'playing' THEN RAISE EXCEPTION 'NOT_PLAYING'; END IF;
  IF now() > r.choose_ends_at THEN RAISE EXCEPTION 'TOO_LATE'; END IF;
  IF now() < r.prepare_ends_at THEN RAISE EXCEPTION 'NOT_YET'; END IF;

  IF v_me = r.creator_id THEN
    IF r.creator_choice IS NOT NULL THEN RAISE EXCEPTION 'ALREADY_CHOSEN'; END IF;
    UPDATE public.rps_rooms SET creator_choice = p_choice WHERE id = p_room_id;
    r.creator_choice := p_choice;
  ELSIF v_me = r.opponent_id THEN
    IF r.opponent_choice IS NOT NULL THEN RAISE EXCEPTION 'ALREADY_CHOSEN'; END IF;
    UPDATE public.rps_rooms SET opponent_choice = p_choice WHERE id = p_room_id;
    r.opponent_choice := p_choice;
  ELSE
    RAISE EXCEPTION 'NOT_A_PLAYER';
  END IF;

  IF r.creator_choice IS NOT NULL AND r.opponent_choice IS NOT NULL THEN
    PERFORM public.rps_settle(p_room_id);
  END IF;

  RETURN jsonb_build_object('ok', true);
END $$;

-- ---------------------------------------------------------------------
-- 12) Rời phòng (chỉ hoàn tiền khi CHƯA bắt đầu)
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_leave_room(p_room_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_me uuid := auth.uid(); r public.rps_rooms%rowtype;
BEGIN
  IF v_me IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
  SELECT * INTO r FROM public.rps_rooms WHERE id = p_room_id FOR UPDATE;
  IF r.id IS NULL THEN RETURN jsonb_build_object('ok', true); END IF;

  IF r.status = 'waiting' AND r.creator_id = v_me THEN
    PERFORM public.rps_add_coin(v_me, r.stake);
    UPDATE public.rps_rooms SET status = 'cancelled', finished_at = now() WHERE id = r.id;
    RETURN jsonb_build_object('ok', true, 'refunded', r.stake);
  END IF;

  -- Trận đã bắt đầu: không thể thoát để lấy lại tiền.
  RETURN jsonb_build_object('ok', false, 'reason', 'MATCH_STARTED');
END $$;

-- ---------------------------------------------------------------------
-- 13) Trạng thái 1 phòng (kèm chat + khán giả) — nguồn dữ liệu realtime
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_room_state(p_room_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_me uuid := auth.uid(); r public.rps_rooms%rowtype; v_out jsonb;
BEGIN
  PERFORM public.rps_tick();
  SELECT * INTO r FROM public.rps_rooms WHERE id = p_room_id;
  IF r.id IS NULL THEN RETURN NULL; END IF;

  IF v_me IS NOT NULL THEN
    INSERT INTO public.rps_viewers (room_id, user_id, last_seen)
    VALUES (p_room_id, v_me, now())
    ON CONFLICT (room_id, user_id) DO UPDATE SET last_seen = now();
  END IF;

  SELECT jsonb_build_object(
    'now', now(),
    'me', v_me,
    'balance', (SELECT COALESCE(gem_balance,0) FROM public.profiles WHERE id = v_me),
    'room', jsonb_build_object(
      'id', r.id, 'code', r.code, 'stake', r.stake, 'status', r.status,
      'creator_id', r.creator_id, 'opponent_id', r.opponent_id,
      'creator_name', (SELECT full_name FROM public.profiles WHERE id = r.creator_id),
      'creator_avatar', (SELECT avatar FROM public.profiles WHERE id = r.creator_id),
      'opponent_name', (SELECT full_name FROM public.profiles WHERE id = r.opponent_id),
      'opponent_avatar', (SELECT avatar FROM public.profiles WHERE id = r.opponent_id),
      'prepare_ends_at', r.prepare_ends_at,
      'choose_ends_at', r.choose_ends_at,
      'winner_id', r.winner_id,
      'is_draw', r.is_draw,
      -- Chỉ lộ lựa chọn khi trận đã kết thúc, hoặc của chính mình.
      'creator_choice', CASE WHEN r.status = 'done' OR v_me = r.creator_id THEN r.creator_choice END,
      'opponent_choice', CASE WHEN r.status = 'done' OR v_me = r.opponent_id THEN r.opponent_choice END,
      'creator_locked', (r.creator_choice IS NOT NULL),
      'opponent_locked', (r.opponent_choice IS NOT NULL)
    ),
    'viewers', (SELECT count(*) FROM public.rps_viewers v
                 WHERE v.room_id = r.id AND v.last_seen > now() - interval '30 seconds'),
    'messages', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
               'id', m.id, 'user_id', m.user_id, 'body', m.body,
               'name', p.full_name, 'avatar', p.avatar, 'created_at', m.created_at
             ) ORDER BY m.id)
        FROM (SELECT * FROM public.rps_messages WHERE room_id = r.id ORDER BY id DESC LIMIT 50) m
        LEFT JOIN public.profiles p ON p.id = m.user_id
    ), '[]'::jsonb)
  ) INTO v_out;
  RETURN v_out;
END $$;

-- ---------------------------------------------------------------------
-- 14) Chat trong phòng
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rps_send_message(p_room_id bigint, p_body text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_me uuid := auth.uid();
BEGIN
  IF v_me IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
  IF char_length(trim(p_body)) = 0 THEN RAISE EXCEPTION 'EMPTY'; END IF;
  IF (SELECT count(*) FROM public.rps_messages
       WHERE user_id = v_me AND created_at > now() - interval '5 seconds') >= 5 THEN
    RAISE EXCEPTION 'RATE_LIMIT';
  END IF;
  INSERT INTO public.rps_messages (room_id, user_id, body)
  VALUES (p_room_id, v_me, left(trim(p_body), 200));
  RETURN jsonb_build_object('ok', true);
END $$;

GRANT EXECUTE ON FUNCTION public.rps_list_rooms()               TO authenticated;
GRANT EXECUTE ON FUNCTION public.rps_active_count()             TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.rps_create_room(bigint)        TO authenticated;
GRANT EXECUTE ON FUNCTION public.rps_join_room(bigint)          TO authenticated;
GRANT EXECUTE ON FUNCTION public.rps_choose(bigint, text)       TO authenticated;
GRANT EXECUTE ON FUNCTION public.rps_leave_room(bigint)         TO authenticated;
GRANT EXECUTE ON FUNCTION public.rps_room_state(bigint)         TO authenticated;
GRANT EXECUTE ON FUNCTION public.rps_send_message(bigint, text) TO authenticated;
