/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as EighteenRouteImport } from './routes/eighteen'
import { Route as FeedbackZaloRouteImport } from './routes/feedback-zalo'
import { Route as FindFwbRouteImport } from './routes/find-fwb'
import { Route as FwbRouteImport } from './routes/fwb'
import { Route as GemHistoryRouteImport } from './routes/gem-history'
import { Route as HuongdanRouteImport } from './routes/huongdan'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as KetNoiBiMatRouteImport } from './routes/ket-noi-bi-mat'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as LoveRouteImport } from './routes/love'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PetRouteImport } from './routes/pet'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QaExploreRouteImport } from './routes/qa-explore'
import { Route as QaSeverLockRouteImport } from './routes/qa-sever-lock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuggestedRouteImport } from './routes/suggested'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VerifyRequiredRouteImport } from './routes/verify-required'
import { Route as VipCommunityRouteImport } from './routes/vip-community'
import { Route as _testBottomNavRouteImport } from './routes/__test.bottom-nav'
import { Route as _testDockRouteImport } from './routes/__test.dock'
import { Route as _testFeedRouteImport } from './routes/__test.feed'
import { Route as _testVideomediaRouteImport } from './routes/__test.videomedia'
import { Route as AccountUserIdRouteImport } from './routes/account.$userId'
import { Route as ChatUserIdRouteImport } from './routes/chat.$userId'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as SettingsPasswordRouteImport } from './routes/settings.password'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletWithdrawRouteImport } from './routes/wallet.withdraw'
import { Route as ApiPublicAdminResetChatRouteImport } from './routes/api/public/admin-reset-chat'
import { Route as ApiPublicAuditReadonlyRouteImport } from './routes/api/public/audit-readonly'
import { Route as ApiPublicAutoApproveCronRouteImport } from './routes/api/public/auto-approve-cron'
import { Route as ApiPublicClientIpRouteImport } from './routes/api/public/client-ip'
import { Route as ApiPublicCloneVideoTrimRouteImport } from './routes/api/public/clone-video-trim'
import { Route as ApiPublicCloudinarySignRouteImport } from './routes/api/public/cloudinary-sign'
import { Route as ApiPublicCrmCardSubmitRouteImport } from './routes/api/public/crm-card-submit'
import { Route as ApiPublicEmergencyPurgeRouteImport } from './routes/api/public/emergency-purge'
import { Route as ApiPublicEmergencyResetRouteImport } from './routes/api/public/emergency-reset'
import { Route as ApiPublicHotMediaRouteImport } from './routes/api/public/hot-media'
import { Route as ApiPublicPurgeChatCronRouteImport } from './routes/api/public/purge-chat-cron'
import { Route as ApiPublicPurgeLogsCronRouteImport } from './routes/api/public/purge-logs-cron'
import { Route as ApiPublicR2DeleteRouteImport } from './routes/api/public/r2-delete'
import { Route as ApiPublicR2SignRouteImport } from './routes/api/public/r2-sign'
import { Route as ApiPublicR2TestRouteImport } from './routes/api/public/r2-test'
import { Route as ApiPublicSb3UploadRouteImport } from './routes/api/public/sb3-upload'
import { Route as ApiPublicSyncContentToS3RouteImport } from './routes/api/public/sync-content-to-s3'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const EighteenRoute = EighteenRouteImport.update({
  id: '/eighteen',
  path: '/eighteen',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackZaloRoute = FeedbackZaloRouteImport.update({
  id: '/feedback-zalo',
  path: '/feedback-zalo',
  getParentRoute: () => rootRouteImport,
} as any)
const FindFwbRoute = FindFwbRouteImport.update({
  id: '/find-fwb',
  path: '/find-fwb',
  getParentRoute: () => rootRouteImport,
} as any)
const FwbRoute = FwbRouteImport.update({
  id: '/fwb',
  path: '/fwb',
  getParentRoute: () => rootRouteImport,
} as any)
const GemHistoryRoute = GemHistoryRouteImport.update({
  id: '/gem-history',
  path: '/gem-history',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongdanRoute = HuongdanRouteImport.update({
  id: '/huongdan',
  path: '/huongdan',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const KetNoiBiMatRoute = KetNoiBiMatRouteImport.update({
  id: '/ket-noi-bi-mat',
  path: '/ket-noi-bi-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveRoute = LoveRouteImport.update({
  id: '/love',
  path: '/love',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PetRoute = PetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QaExploreRoute = QaExploreRouteImport.update({
  id: '/qa-explore',
  path: '/qa-explore',
  getParentRoute: () => rootRouteImport,
} as any)
const QaSeverLockRoute = QaSeverLockRouteImport.update({
  id: '/qa-sever-lock',
  path: '/qa-sever-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestedRoute = SuggestedRouteImport.update({
  id: '/suggested',
  path: '/suggested',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRequiredRoute = VerifyRequiredRouteImport.update({
  id: '/verify-required',
  path: '/verify-required',
  getParentRoute: () => rootRouteImport,
} as any)
const VipCommunityRoute = VipCommunityRouteImport.update({
  id: '/vip-community',
  path: '/vip-community',
  getParentRoute: () => rootRouteImport,
} as any)
const _testBottomNavRoute = _testBottomNavRouteImport.update({
  id: '/__test/bottom-nav',
  path: '/bottom-nav',
  getParentRoute: () => rootRouteImport,
} as any)
const _testDockRoute = _testDockRouteImport.update({
  id: '/__test/dock',
  path: '/dock',
  getParentRoute: () => rootRouteImport,
} as any)
const _testFeedRoute = _testFeedRouteImport.update({
  id: '/__test/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const _testVideomediaRoute = _testVideomediaRouteImport.update({
  id: '/__test/videomedia',
  path: '/videomedia',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUserIdRoute = AccountUserIdRouteImport.update({
  id: '/account/$userId',
  path: '/account/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatUserIdRoute = ChatUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ChatRoute,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const SettingsPasswordRoute = SettingsPasswordRouteImport.update({
  id: '/settings/password',
  path: '/settings/password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletWithdrawRoute = WalletWithdrawRouteImport.update({
  id: '/wallet/withdraw',
  path: '/wallet/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminResetChatRoute = ApiPublicAdminResetChatRouteImport.update({
  id: '/api/public/admin-reset-chat',
  path: '/api/public/admin-reset-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuditReadonlyRoute = ApiPublicAuditReadonlyRouteImport.update({
  id: '/api/public/audit-readonly',
  path: '/api/public/audit-readonly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutoApproveCronRoute =
  ApiPublicAutoApproveCronRouteImport.update({
    id: '/api/public/auto-approve-cron',
    path: '/api/public/auto-approve-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClientIpRoute = ApiPublicClientIpRouteImport.update({
  id: '/api/public/client-ip',
  path: '/api/public/client-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloneVideoTrimRoute = ApiPublicCloneVideoTrimRouteImport.update({
  id: '/api/public/clone-video-trim',
  path: '/api/public/clone-video-trim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudinarySignRoute = ApiPublicCloudinarySignRouteImport.update({
  id: '/api/public/cloudinary-sign',
  path: '/api/public/cloudinary-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmCardSubmitRoute = ApiPublicCrmCardSubmitRouteImport.update({
  id: '/api/public/crm-card-submit',
  path: '/api/public/crm-card-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmergencyPurgeRoute = ApiPublicEmergencyPurgeRouteImport.update({
  id: '/api/public/emergency-purge',
  path: '/api/public/emergency-purge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmergencyResetRoute = ApiPublicEmergencyResetRouteImport.update({
  id: '/api/public/emergency-reset',
  path: '/api/public/emergency-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHotMediaRoute = ApiPublicHotMediaRouteImport.update({
  id: '/api/public/hot-media',
  path: '/api/public/hot-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPurgeChatCronRoute = ApiPublicPurgeChatCronRouteImport.update({
  id: '/api/public/purge-chat-cron',
  path: '/api/public/purge-chat-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPurgeLogsCronRoute = ApiPublicPurgeLogsCronRouteImport.update({
  id: '/api/public/purge-logs-cron',
  path: '/api/public/purge-logs-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicR2DeleteRoute = ApiPublicR2DeleteRouteImport.update({
  id: '/api/public/r2-delete',
  path: '/api/public/r2-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicR2SignRoute = ApiPublicR2SignRouteImport.update({
  id: '/api/public/r2-sign',
  path: '/api/public/r2-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicR2TestRoute = ApiPublicR2TestRouteImport.update({
  id: '/api/public/r2-test',
  path: '/api/public/r2-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSb3UploadRoute = ApiPublicSb3UploadRouteImport.update({
  id: '/api/public/sb3-upload',
  path: '/api/public/sb3-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncContentToS3Route =
  ApiPublicSyncContentToS3RouteImport.update({
    id: '/api/public/sync-content-to-s3',
    path: '/api/public/sync-content-to-s3',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/blocked': typeof BlockedRoute
  '/chat': typeof ChatRouteWithChildren
  '/connect': typeof ConnectRoute
  '/eighteen': typeof EighteenRoute
  '/feedback-zalo': typeof FeedbackZaloRoute
  '/find-fwb': typeof FindFwbRoute
  '/fwb': typeof FwbRoute
  '/gem-history': typeof GemHistoryRoute
  '/huongdan': typeof HuongdanRoute
  '/inventory': typeof InventoryRoute
  '/ket-noi-bi-mat': typeof KetNoiBiMatRoute
  '/locked': typeof LockedRoute
  '/love': typeof LoveRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/pet': typeof PetRoute
  '/profile': typeof ProfileRouteWithChildren
  '/qa-explore': typeof QaExploreRoute
  '/qa-sever-lock': typeof QaSeverLockRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggested': typeof SuggestedRoute
  '/verify': typeof VerifyRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/vip-community': typeof VipCommunityRoute
  '/bottom-nav': typeof _testBottomNavRoute
  '/dock': typeof _testDockRoute
  '/feed': typeof _testFeedRoute
  '/videomedia': typeof _testVideomediaRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$userId': typeof UUserIdRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/public/admin-reset-chat': typeof ApiPublicAdminResetChatRoute
  '/api/public/audit-readonly': typeof ApiPublicAuditReadonlyRoute
  '/api/public/auto-approve-cron': typeof ApiPublicAutoApproveCronRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/clone-video-trim': typeof ApiPublicCloneVideoTrimRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/crm-card-submit': typeof ApiPublicCrmCardSubmitRoute
  '/api/public/emergency-purge': typeof ApiPublicEmergencyPurgeRoute
  '/api/public/emergency-reset': typeof ApiPublicEmergencyResetRoute
  '/api/public/hot-media': typeof ApiPublicHotMediaRoute
  '/api/public/purge-chat-cron': typeof ApiPublicPurgeChatCronRoute
  '/api/public/purge-logs-cron': typeof ApiPublicPurgeLogsCronRoute
  '/api/public/r2-delete': typeof ApiPublicR2DeleteRoute
  '/api/public/r2-sign': typeof ApiPublicR2SignRoute
  '/api/public/r2-test': typeof ApiPublicR2TestRoute
  '/api/public/sb3-upload': typeof ApiPublicSb3UploadRoute
  '/api/public/sync-content-to-s3': typeof ApiPublicSyncContentToS3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/blocked': typeof BlockedRoute
  '/chat': typeof ChatRouteWithChildren
  '/connect': typeof ConnectRoute
  '/eighteen': typeof EighteenRoute
  '/feedback-zalo': typeof FeedbackZaloRoute
  '/find-fwb': typeof FindFwbRoute
  '/fwb': typeof FwbRoute
  '/gem-history': typeof GemHistoryRoute
  '/huongdan': typeof HuongdanRoute
  '/inventory': typeof InventoryRoute
  '/ket-noi-bi-mat': typeof KetNoiBiMatRoute
  '/locked': typeof LockedRoute
  '/love': typeof LoveRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/pet': typeof PetRoute
  '/profile': typeof ProfileRouteWithChildren
  '/qa-explore': typeof QaExploreRoute
  '/qa-sever-lock': typeof QaSeverLockRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggested': typeof SuggestedRoute
  '/verify': typeof VerifyRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/vip-community': typeof VipCommunityRoute
  '/bottom-nav': typeof _testBottomNavRoute
  '/dock': typeof _testDockRoute
  '/feed': typeof _testFeedRoute
  '/videomedia': typeof _testVideomediaRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$userId': typeof UUserIdRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/wallet': typeof WalletIndexRoute
  '/api/public/admin-reset-chat': typeof ApiPublicAdminResetChatRoute
  '/api/public/audit-readonly': typeof ApiPublicAuditReadonlyRoute
  '/api/public/auto-approve-cron': typeof ApiPublicAutoApproveCronRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/clone-video-trim': typeof ApiPublicCloneVideoTrimRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/crm-card-submit': typeof ApiPublicCrmCardSubmitRoute
  '/api/public/emergency-purge': typeof ApiPublicEmergencyPurgeRoute
  '/api/public/emergency-reset': typeof ApiPublicEmergencyResetRoute
  '/api/public/hot-media': typeof ApiPublicHotMediaRoute
  '/api/public/purge-chat-cron': typeof ApiPublicPurgeChatCronRoute
  '/api/public/purge-logs-cron': typeof ApiPublicPurgeLogsCronRoute
  '/api/public/r2-delete': typeof ApiPublicR2DeleteRoute
  '/api/public/r2-sign': typeof ApiPublicR2SignRoute
  '/api/public/r2-test': typeof ApiPublicR2TestRoute
  '/api/public/sb3-upload': typeof ApiPublicSb3UploadRoute
  '/api/public/sync-content-to-s3': typeof ApiPublicSyncContentToS3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/blocked': typeof BlockedRoute
  '/chat': typeof ChatRouteWithChildren
  '/connect': typeof ConnectRoute
  '/eighteen': typeof EighteenRoute
  '/feedback-zalo': typeof FeedbackZaloRoute
  '/find-fwb': typeof FindFwbRoute
  '/fwb': typeof FwbRoute
  '/gem-history': typeof GemHistoryRoute
  '/huongdan': typeof HuongdanRoute
  '/inventory': typeof InventoryRoute
  '/ket-noi-bi-mat': typeof KetNoiBiMatRoute
  '/locked': typeof LockedRoute
  '/love': typeof LoveRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/pet': typeof PetRoute
  '/profile': typeof ProfileRouteWithChildren
  '/qa-explore': typeof QaExploreRoute
  '/qa-sever-lock': typeof QaSeverLockRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suggested': typeof SuggestedRoute
  '/verify': typeof VerifyRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/vip-community': typeof VipCommunityRoute
  '/__test/bottom-nav': typeof _testBottomNavRoute
  '/__test/dock': typeof _testDockRoute
  '/__test/feed': typeof _testFeedRoute
  '/__test/videomedia': typeof _testVideomediaRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/chat/$userId': typeof ChatUserIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/u/$userId': typeof UUserIdRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/public/admin-reset-chat': typeof ApiPublicAdminResetChatRoute
  '/api/public/audit-readonly': typeof ApiPublicAuditReadonlyRoute
  '/api/public/auto-approve-cron': typeof ApiPublicAutoApproveCronRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/clone-video-trim': typeof ApiPublicCloneVideoTrimRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/crm-card-submit': typeof ApiPublicCrmCardSubmitRoute
  '/api/public/emergency-purge': typeof ApiPublicEmergencyPurgeRoute
  '/api/public/emergency-reset': typeof ApiPublicEmergencyResetRoute
  '/api/public/hot-media': typeof ApiPublicHotMediaRoute
  '/api/public/purge-chat-cron': typeof ApiPublicPurgeChatCronRoute
  '/api/public/purge-logs-cron': typeof ApiPublicPurgeLogsCronRoute
  '/api/public/r2-delete': typeof ApiPublicR2DeleteRoute
  '/api/public/r2-sign': typeof ApiPublicR2SignRoute
  '/api/public/r2-test': typeof ApiPublicR2TestRoute
  '/api/public/sb3-upload': typeof ApiPublicSb3UploadRoute
  '/api/public/sync-content-to-s3': typeof ApiPublicSyncContentToS3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/activity'
    | '/blocked'
    | '/chat'
    | '/connect'
    | '/eighteen'
    | '/feedback-zalo'
    | '/find-fwb'
    | '/fwb'
    | '/gem-history'
    | '/huongdan'
    | '/inventory'
    | '/ket-noi-bi-mat'
    | '/locked'
    | '/love'
    | '/maintenance'
    | '/notifications'
    | '/pet'
    | '/profile'
    | '/qa-explore'
    | '/qa-sever-lock'
    | '/sitemap.xml'
    | '/suggested'
    | '/verify'
    | '/verify-required'
    | '/vip-community'
    | '/bottom-nav'
    | '/dock'
    | '/feed'
    | '/videomedia'
    | '/account/$userId'
    | '/chat/$userId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/settings/password'
    | '/settings/profile'
    | '/u/$userId'
    | '/wallet/withdraw'
    | '/wallet/'
    | '/api/public/admin-reset-chat'
    | '/api/public/audit-readonly'
    | '/api/public/auto-approve-cron'
    | '/api/public/client-ip'
    | '/api/public/clone-video-trim'
    | '/api/public/cloudinary-sign'
    | '/api/public/crm-card-submit'
    | '/api/public/emergency-purge'
    | '/api/public/emergency-reset'
    | '/api/public/hot-media'
    | '/api/public/purge-chat-cron'
    | '/api/public/purge-logs-cron'
    | '/api/public/r2-delete'
    | '/api/public/r2-sign'
    | '/api/public/r2-test'
    | '/api/public/sb3-upload'
    | '/api/public/sync-content-to-s3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/activity'
    | '/blocked'
    | '/chat'
    | '/connect'
    | '/eighteen'
    | '/feedback-zalo'
    | '/find-fwb'
    | '/fwb'
    | '/gem-history'
    | '/huongdan'
    | '/inventory'
    | '/ket-noi-bi-mat'
    | '/locked'
    | '/love'
    | '/maintenance'
    | '/notifications'
    | '/pet'
    | '/profile'
    | '/qa-explore'
    | '/qa-sever-lock'
    | '/sitemap.xml'
    | '/suggested'
    | '/verify'
    | '/verify-required'
    | '/vip-community'
    | '/bottom-nav'
    | '/dock'
    | '/feed'
    | '/videomedia'
    | '/account/$userId'
    | '/chat/$userId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/settings/password'
    | '/settings/profile'
    | '/u/$userId'
    | '/wallet/withdraw'
    | '/wallet'
    | '/api/public/admin-reset-chat'
    | '/api/public/audit-readonly'
    | '/api/public/auto-approve-cron'
    | '/api/public/client-ip'
    | '/api/public/clone-video-trim'
    | '/api/public/cloudinary-sign'
    | '/api/public/crm-card-submit'
    | '/api/public/emergency-purge'
    | '/api/public/emergency-reset'
    | '/api/public/hot-media'
    | '/api/public/purge-chat-cron'
    | '/api/public/purge-logs-cron'
    | '/api/public/r2-delete'
    | '/api/public/r2-sign'
    | '/api/public/r2-test'
    | '/api/public/sb3-upload'
    | '/api/public/sync-content-to-s3'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/activity'
    | '/blocked'
    | '/chat'
    | '/connect'
    | '/eighteen'
    | '/feedback-zalo'
    | '/find-fwb'
    | '/fwb'
    | '/gem-history'
    | '/huongdan'
    | '/inventory'
    | '/ket-noi-bi-mat'
    | '/locked'
    | '/love'
    | '/maintenance'
    | '/notifications'
    | '/pet'
    | '/profile'
    | '/qa-explore'
    | '/qa-sever-lock'
    | '/sitemap.xml'
    | '/suggested'
    | '/verify'
    | '/verify-required'
    | '/vip-community'
    | '/__test/bottom-nav'
    | '/__test/dock'
    | '/__test/feed'
    | '/__test/videomedia'
    | '/account/$userId'
    | '/chat/$userId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/settings/password'
    | '/settings/profile'
    | '/u/$userId'
    | '/wallet/withdraw'
    | '/wallet/'
    | '/api/public/admin-reset-chat'
    | '/api/public/audit-readonly'
    | '/api/public/auto-approve-cron'
    | '/api/public/client-ip'
    | '/api/public/clone-video-trim'
    | '/api/public/cloudinary-sign'
    | '/api/public/crm-card-submit'
    | '/api/public/emergency-purge'
    | '/api/public/emergency-reset'
    | '/api/public/hot-media'
    | '/api/public/purge-chat-cron'
    | '/api/public/purge-logs-cron'
    | '/api/public/r2-delete'
    | '/api/public/r2-sign'
    | '/api/public/r2-test'
    | '/api/public/sb3-upload'
    | '/api/public/sync-content-to-s3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ActivityRoute: typeof ActivityRoute
  BlockedRoute: typeof BlockedRoute
  ChatRoute: typeof ChatRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  EighteenRoute: typeof EighteenRoute
  FeedbackZaloRoute: typeof FeedbackZaloRoute
  FindFwbRoute: typeof FindFwbRoute
  FwbRoute: typeof FwbRoute
  GemHistoryRoute: typeof GemHistoryRoute
  HuongdanRoute: typeof HuongdanRoute
  InventoryRoute: typeof InventoryRoute
  KetNoiBiMatRoute: typeof KetNoiBiMatRoute
  LockedRoute: typeof LockedRoute
  LoveRoute: typeof LoveRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotificationsRoute: typeof NotificationsRoute
  PetRoute: typeof PetRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  QaExploreRoute: typeof QaExploreRoute
  QaSeverLockRoute: typeof QaSeverLockRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuggestedRoute: typeof SuggestedRoute
  VerifyRoute: typeof VerifyRoute
  VerifyRequiredRoute: typeof VerifyRequiredRoute
  VipCommunityRoute: typeof VipCommunityRoute
  _testBottomNavRoute: typeof _testBottomNavRoute
  _testDockRoute: typeof _testDockRoute
  _testFeedRoute: typeof _testFeedRoute
  _testVideomediaRoute: typeof _testVideomediaRoute
  AccountUserIdRoute: typeof AccountUserIdRoute
  PostPostIdRoute: typeof PostPostIdRoute
  SettingsPasswordRoute: typeof SettingsPasswordRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  UUserIdRoute: typeof UUserIdRoute
  WalletWithdrawRoute: typeof WalletWithdrawRoute
  WalletIndexRoute: typeof WalletIndexRoute
  ApiPublicAdminResetChatRoute: typeof ApiPublicAdminResetChatRoute
  ApiPublicAuditReadonlyRoute: typeof ApiPublicAuditReadonlyRoute
  ApiPublicAutoApproveCronRoute: typeof ApiPublicAutoApproveCronRoute
  ApiPublicClientIpRoute: typeof ApiPublicClientIpRoute
  ApiPublicCloneVideoTrimRoute: typeof ApiPublicCloneVideoTrimRoute
  ApiPublicCloudinarySignRoute: typeof ApiPublicCloudinarySignRoute
  ApiPublicCrmCardSubmitRoute: typeof ApiPublicCrmCardSubmitRoute
  ApiPublicEmergencyPurgeRoute: typeof ApiPublicEmergencyPurgeRoute
  ApiPublicEmergencyResetRoute: typeof ApiPublicEmergencyResetRoute
  ApiPublicHotMediaRoute: typeof ApiPublicHotMediaRoute
  ApiPublicPurgeChatCronRoute: typeof ApiPublicPurgeChatCronRoute
  ApiPublicPurgeLogsCronRoute: typeof ApiPublicPurgeLogsCronRoute
  ApiPublicR2DeleteRoute: typeof ApiPublicR2DeleteRoute
  ApiPublicR2SignRoute: typeof ApiPublicR2SignRoute
  ApiPublicR2TestRoute: typeof ApiPublicR2TestRoute
  ApiPublicSb3UploadRoute: typeof ApiPublicSb3UploadRoute
  ApiPublicSyncContentToS3Route: typeof ApiPublicSyncContentToS3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eighteen': {
      id: '/eighteen'
      path: '/eighteen'
      fullPath: '/eighteen'
      preLoaderRoute: typeof EighteenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-zalo': {
      id: '/feedback-zalo'
      path: '/feedback-zalo'
      fullPath: '/feedback-zalo'
      preLoaderRoute: typeof FeedbackZaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-fwb': {
      id: '/find-fwb'
      path: '/find-fwb'
      fullPath: '/find-fwb'
      preLoaderRoute: typeof FindFwbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fwb': {
      id: '/fwb'
      path: '/fwb'
      fullPath: '/fwb'
      preLoaderRoute: typeof FwbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gem-history': {
      id: '/gem-history'
      path: '/gem-history'
      fullPath: '/gem-history'
      preLoaderRoute: typeof GemHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huongdan': {
      id: '/huongdan'
      path: '/huongdan'
      fullPath: '/huongdan'
      preLoaderRoute: typeof HuongdanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ket-noi-bi-mat': {
      id: '/ket-noi-bi-mat'
      path: '/ket-noi-bi-mat'
      fullPath: '/ket-noi-bi-mat'
      preLoaderRoute: typeof KetNoiBiMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love': {
      id: '/love'
      path: '/love'
      fullPath: '/love'
      preLoaderRoute: typeof LoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet': {
      id: '/pet'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof PetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-explore': {
      id: '/qa-explore'
      path: '/qa-explore'
      fullPath: '/qa-explore'
      preLoaderRoute: typeof QaExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-sever-lock': {
      id: '/qa-sever-lock'
      path: '/qa-sever-lock'
      fullPath: '/qa-sever-lock'
      preLoaderRoute: typeof QaSeverLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggested': {
      id: '/suggested'
      path: '/suggested'
      fullPath: '/suggested'
      preLoaderRoute: typeof SuggestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-required': {
      id: '/verify-required'
      path: '/verify-required'
      fullPath: '/verify-required'
      preLoaderRoute: typeof VerifyRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-community': {
      id: '/vip-community'
      path: '/vip-community'
      fullPath: '/vip-community'
      preLoaderRoute: typeof VipCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__test/bottom-nav': {
      id: '/__test/bottom-nav'
      path: '/bottom-nav'
      fullPath: '/bottom-nav'
      preLoaderRoute: typeof _testBottomNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__test/dock': {
      id: '/__test/dock'
      path: '/dock'
      fullPath: '/dock'
      preLoaderRoute: typeof _testDockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__test/feed': {
      id: '/__test/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof _testFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__test/videomedia': {
      id: '/__test/videomedia'
      path: '/videomedia'
      fullPath: '/videomedia'
      preLoaderRoute: typeof _testVideomediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$userId': {
      id: '/account/$userId'
      path: '/account/$userId'
      fullPath: '/account/$userId'
      preLoaderRoute: typeof AccountUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$userId': {
      id: '/chat/$userId'
      path: '/$userId'
      fullPath: '/chat/$userId'
      preLoaderRoute: typeof ChatUserIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/settings/password': {
      id: '/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/withdraw': {
      id: '/wallet/withdraw'
      path: '/wallet/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof WalletWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-reset-chat': {
      id: '/api/public/admin-reset-chat'
      path: '/api/public/admin-reset-chat'
      fullPath: '/api/public/admin-reset-chat'
      preLoaderRoute: typeof ApiPublicAdminResetChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit-readonly': {
      id: '/api/public/audit-readonly'
      path: '/api/public/audit-readonly'
      fullPath: '/api/public/audit-readonly'
      preLoaderRoute: typeof ApiPublicAuditReadonlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auto-approve-cron': {
      id: '/api/public/auto-approve-cron'
      path: '/api/public/auto-approve-cron'
      fullPath: '/api/public/auto-approve-cron'
      preLoaderRoute: typeof ApiPublicAutoApproveCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-ip': {
      id: '/api/public/client-ip'
      path: '/api/public/client-ip'
      fullPath: '/api/public/client-ip'
      preLoaderRoute: typeof ApiPublicClientIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clone-video-trim': {
      id: '/api/public/clone-video-trim'
      path: '/api/public/clone-video-trim'
      fullPath: '/api/public/clone-video-trim'
      preLoaderRoute: typeof ApiPublicCloneVideoTrimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary-sign': {
      id: '/api/public/cloudinary-sign'
      path: '/api/public/cloudinary-sign'
      fullPath: '/api/public/cloudinary-sign'
      preLoaderRoute: typeof ApiPublicCloudinarySignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm-card-submit': {
      id: '/api/public/crm-card-submit'
      path: '/api/public/crm-card-submit'
      fullPath: '/api/public/crm-card-submit'
      preLoaderRoute: typeof ApiPublicCrmCardSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emergency-purge': {
      id: '/api/public/emergency-purge'
      path: '/api/public/emergency-purge'
      fullPath: '/api/public/emergency-purge'
      preLoaderRoute: typeof ApiPublicEmergencyPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emergency-reset': {
      id: '/api/public/emergency-reset'
      path: '/api/public/emergency-reset'
      fullPath: '/api/public/emergency-reset'
      preLoaderRoute: typeof ApiPublicEmergencyResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hot-media': {
      id: '/api/public/hot-media'
      path: '/api/public/hot-media'
      fullPath: '/api/public/hot-media'
      preLoaderRoute: typeof ApiPublicHotMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/purge-chat-cron': {
      id: '/api/public/purge-chat-cron'
      path: '/api/public/purge-chat-cron'
      fullPath: '/api/public/purge-chat-cron'
      preLoaderRoute: typeof ApiPublicPurgeChatCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/purge-logs-cron': {
      id: '/api/public/purge-logs-cron'
      path: '/api/public/purge-logs-cron'
      fullPath: '/api/public/purge-logs-cron'
      preLoaderRoute: typeof ApiPublicPurgeLogsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r2-delete': {
      id: '/api/public/r2-delete'
      path: '/api/public/r2-delete'
      fullPath: '/api/public/r2-delete'
      preLoaderRoute: typeof ApiPublicR2DeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r2-sign': {
      id: '/api/public/r2-sign'
      path: '/api/public/r2-sign'
      fullPath: '/api/public/r2-sign'
      preLoaderRoute: typeof ApiPublicR2SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r2-test': {
      id: '/api/public/r2-test'
      path: '/api/public/r2-test'
      fullPath: '/api/public/r2-test'
      preLoaderRoute: typeof ApiPublicR2TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sb3-upload': {
      id: '/api/public/sb3-upload'
      path: '/api/public/sb3-upload'
      fullPath: '/api/public/sb3-upload'
      preLoaderRoute: typeof ApiPublicSb3UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-content-to-s3': {
      id: '/api/public/sync-content-to-s3'
      path: '/api/public/sync-content-to-s3'
      fullPath: '/api/public/sync-content-to-s3'
      preLoaderRoute: typeof ApiPublicSyncContentToS3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatUserIdRoute: typeof ChatUserIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatUserIdRoute: ChatUserIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ActivityRoute: ActivityRoute,
  BlockedRoute: BlockedRoute,
  ChatRoute: ChatRouteWithChildren,
  ConnectRoute: ConnectRoute,
  EighteenRoute: EighteenRoute,
  FeedbackZaloRoute: FeedbackZaloRoute,
  FindFwbRoute: FindFwbRoute,
  FwbRoute: FwbRoute,
  GemHistoryRoute: GemHistoryRoute,
  HuongdanRoute: HuongdanRoute,
  InventoryRoute: InventoryRoute,
  KetNoiBiMatRoute: KetNoiBiMatRoute,
  LockedRoute: LockedRoute,
  LoveRoute: LoveRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotificationsRoute: NotificationsRoute,
  PetRoute: PetRoute,
  ProfileRoute: ProfileRouteWithChildren,
  QaExploreRoute: QaExploreRoute,
  QaSeverLockRoute: QaSeverLockRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuggestedRoute: SuggestedRoute,
  VerifyRoute: VerifyRoute,
  VerifyRequiredRoute: VerifyRequiredRoute,
  VipCommunityRoute: VipCommunityRoute,
  _testBottomNavRoute: _testBottomNavRoute,
  _testDockRoute: _testDockRoute,
  _testFeedRoute: _testFeedRoute,
  _testVideomediaRoute: _testVideomediaRoute,
  AccountUserIdRoute: AccountUserIdRoute,
  PostPostIdRoute: PostPostIdRoute,
  SettingsPasswordRoute: SettingsPasswordRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  UUserIdRoute: UUserIdRoute,
  WalletWithdrawRoute: WalletWithdrawRoute,
  WalletIndexRoute: WalletIndexRoute,
  ApiPublicAdminResetChatRoute: ApiPublicAdminResetChatRoute,
  ApiPublicAuditReadonlyRoute: ApiPublicAuditReadonlyRoute,
  ApiPublicAutoApproveCronRoute: ApiPublicAutoApproveCronRoute,
  ApiPublicClientIpRoute: ApiPublicClientIpRoute,
  ApiPublicCloneVideoTrimRoute: ApiPublicCloneVideoTrimRoute,
  ApiPublicCloudinarySignRoute: ApiPublicCloudinarySignRoute,
  ApiPublicCrmCardSubmitRoute: ApiPublicCrmCardSubmitRoute,
  ApiPublicEmergencyPurgeRoute: ApiPublicEmergencyPurgeRoute,
  ApiPublicEmergencyResetRoute: ApiPublicEmergencyResetRoute,
  ApiPublicHotMediaRoute: ApiPublicHotMediaRoute,
  ApiPublicPurgeChatCronRoute: ApiPublicPurgeChatCronRoute,
  ApiPublicPurgeLogsCronRoute: ApiPublicPurgeLogsCronRoute,
  ApiPublicR2DeleteRoute: ApiPublicR2DeleteRoute,
  ApiPublicR2SignRoute: ApiPublicR2SignRoute,
  ApiPublicR2TestRoute: ApiPublicR2TestRoute,
  ApiPublicSb3UploadRoute: ApiPublicSb3UploadRoute,
  ApiPublicSyncContentToS3Route: ApiPublicSyncContentToS3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
