/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyRequiredRouteImport } from './routes/verify-required'
import { Route as _testFeedRouteImport } from './routes/__test.feed'
import { Route as ApiPublicClientIpRouteImport } from './routes/api/public/client-ip'
import { Route as ApiPublicCloudinarySignRouteImport } from './routes/api/public/cloudinary-sign'
import { Route as ApiPublicPurgeChatCronRouteImport } from './routes/api/public/purge-chat-cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRequiredRoute = VerifyRequiredRouteImport.update({
  id: '/verify-required',
  path: '/verify-required',
  getParentRoute: () => rootRouteImport,
} as any)
const _testFeedRoute = _testFeedRouteImport.update({
  id: '/__test/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientIpRoute = ApiPublicClientIpRouteImport.update({
  id: '/api/public/client-ip',
  path: '/api/public/client-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudinarySignRoute = ApiPublicCloudinarySignRouteImport.update({
  id: '/api/public/cloudinary-sign',
  path: '/api/public/cloudinary-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPurgeChatCronRoute = ApiPublicPurgeChatCronRouteImport.update({
  id: '/api/public/purge-chat-cron',
  path: '/api/public/purge-chat-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blocked': typeof BlockedRoute
  '/locked': typeof LockedRoute
  '/maintenance': typeof MaintenanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/feed': typeof _testFeedRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/purge-chat-cron': typeof ApiPublicPurgeChatCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blocked': typeof BlockedRoute
  '/locked': typeof LockedRoute
  '/maintenance': typeof MaintenanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/feed': typeof _testFeedRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/purge-chat-cron': typeof ApiPublicPurgeChatCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/blocked': typeof BlockedRoute
  '/locked': typeof LockedRoute
  '/maintenance': typeof MaintenanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/__test/feed': typeof _testFeedRoute
  '/api/public/client-ip': typeof ApiPublicClientIpRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/purge-chat-cron': typeof ApiPublicPurgeChatCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/blocked'
    | '/locked'
    | '/maintenance'
    | '/sitemap.xml'
    | '/verify-required'
    | '/feed'
    | '/api/public/client-ip'
    | '/api/public/cloudinary-sign'
    | '/api/public/purge-chat-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/blocked'
    | '/locked'
    | '/maintenance'
    | '/sitemap.xml'
    | '/verify-required'
    | '/feed'
    | '/api/public/client-ip'
    | '/api/public/cloudinary-sign'
    | '/api/public/purge-chat-cron'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/blocked'
    | '/locked'
    | '/maintenance'
    | '/sitemap.xml'
    | '/verify-required'
    | '/__test/feed'
    | '/api/public/client-ip'
    | '/api/public/cloudinary-sign'
    | '/api/public/purge-chat-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BlockedRoute: typeof BlockedRoute
  LockedRoute: typeof LockedRoute
  MaintenanceRoute: typeof MaintenanceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRequiredRoute: typeof VerifyRequiredRoute
  _testFeedRoute: typeof _testFeedRoute
  ApiPublicClientIpRoute: typeof ApiPublicClientIpRoute
  ApiPublicCloudinarySignRoute: typeof ApiPublicCloudinarySignRoute
  ApiPublicPurgeChatCronRoute: typeof ApiPublicPurgeChatCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-required': {
      id: '/verify-required'
      path: '/verify-required'
      fullPath: '/verify-required'
      preLoaderRoute: typeof VerifyRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__test/feed': {
      id: '/__test/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof _testFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-ip': {
      id: '/api/public/client-ip'
      path: '/api/public/client-ip'
      fullPath: '/api/public/client-ip'
      preLoaderRoute: typeof ApiPublicClientIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary-sign': {
      id: '/api/public/cloudinary-sign'
      path: '/api/public/cloudinary-sign'
      fullPath: '/api/public/cloudinary-sign'
      preLoaderRoute: typeof ApiPublicCloudinarySignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/purge-chat-cron': {
      id: '/api/public/purge-chat-cron'
      path: '/api/public/purge-chat-cron'
      fullPath: '/api/public/purge-chat-cron'
      preLoaderRoute: typeof ApiPublicPurgeChatCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BlockedRoute: BlockedRoute,
  LockedRoute: LockedRoute,
  MaintenanceRoute: MaintenanceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRequiredRoute: VerifyRequiredRoute,
  _testFeedRoute: _testFeedRoute,
  ApiPublicClientIpRoute: ApiPublicClientIpRoute,
  ApiPublicCloudinarySignRoute: ApiPublicCloudinarySignRoute,
  ApiPublicPurgeChatCronRoute: ApiPublicPurgeChatCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
